### Variables
@baseUrl = http://localhost:3000/api
@contentType = application/json

### Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "user1@test.com",
    "password": "password"
}

### Create a new event
# @name createEvent
POST {{baseUrl}}/events
Content-Type: {{contentType}}

{
    "name": "Event Test 1"
}

### Variables for response testing
@eventId = {{createEvent.response.body.$.data.id}}

### Get all events
GET {{baseUrl}}/events
Content-Type: {{contentType}}

### Get a specific event
GET {{baseUrl}}/events/{{eventId}}
Content-Type: {{contentType}}

### Update a event
PUT {{baseUrl}}/events/{{eventId}}
Content-Type: {{contentType}}

{
    "name": "Event Test 1 updated",
    "lat": 12.9715987
}

### Delete a event
DELETE {{baseUrl}}/events/{{eventId}}
Content-Type: {{contentType}}
