### Variables
@baseUrl = http://localhost:3000/api
@contentType = application/json

### Create a new user
# @name createUser
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
    "username": "johndoe",
    "password": "securePassword123",
    "role": "teacher"
}

### Variables for response testing
@userId = {{createUser.response.body.$.data.id}}

### Get all users
GET {{baseUrl}}/users
Content-Type: {{contentType}}

### Get a specific user
GET {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}

### Update a user
PUT {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}

{
    "username": "johndoe_updated",
    "role": "admin"
}

### Delete a user
DELETE {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}
